name: Make thesis

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pandoc
      uses: pandoc/actions/setup@main
      with:
        version: 3.7.0.2

    - name: Install pandoc-crossref
      run: |
        curl -LO https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.20/pandoc-crossref-Linux-X64.tar.xz
        tar -xvf pandoc-crossref-Linux-X64.tar.xz
        sudo mv pandoc-crossref /usr/local/bin/

    - name: Install ttf-mscorefonts-installer
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install -y ttf-mscorefonts-installer

    - name: Refresh font cache
      run: sudo fc-cache -f -v

    - name: Install latex
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-luatex texlive-lang-cyrillic texlive-fonts-recommended texlive-fonts-extra
        # Verify all necessary tools are installed
        pdflatex --version
        bibtex --version

    - name: Install Make, Inkscape, Graphviz and LibreOffice
      run: |
        sudo apt-get install -y make inkscape graphviz libreoffice

    - name: Make pdf
      run: make -j publish

    - name: Archive published pdfs
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: |
          publish
